# action.yml
name: 'Atom Package GitHub Action'
description: 'Test and upload an Atom package'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
  test-status:
    description: 'Status of the test'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.who-to-greet }}
