name: CI

on: [push]

jobs:
  build-linux-stable:
    runs-on: ubuntu-latest
    env:
      TRAVIS_OS_NAME: linux
      ATOM_CHANNEL: stable
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get package script
      run: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
    - name: Set script permissions
      run: chmod u+x build-package.sh
    - name: Build package
      run: ./build-package.sh

  build-linux-beta:
    runs-on: ubuntu-latest
    env:
      TRAVIS_OS_NAME: linux
      ATOM_CHANNEL: beta
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get package script
      run: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
    - name: Set script permissions
      run: chmod u+x build-package.sh
    - name: Build package
      run: ./build-package.sh

  build-macos-stable:
    runs-on: macOS-latest
    env:
      TRAVIS_OS_NAME: osx
      ATOM_CHANNEL: stable
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get package script
      run: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
    - name: Set script permissions
      run: chmod u+x build-package.sh
    - name: Build package
      run: ./build-package.sh

  build-macos-beta:
    runs-on: macOS-latest
    env:
      TRAVIS_OS_NAME: osx
      ATOM_CHANNEL: beta
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get package script
      run: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
    - name: Set script permissions
      run: chmod u+x build-package.sh
    - name: Build package
      run: ./build-package.sh

  build-windows-stable:
    runs-on: windows-latest
    env:
      ATOM_LINT_WITH_BUNDLED_NODE: true
      ATOM_CHANNEL: stable
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run package script
        run: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

  build-windows-beta:
    runs-on: windows-latest
    env:
      ATOM_LINT_WITH_BUNDLED_NODE: true
      ATOM_CHANNEL: beta
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run package script
        run: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))
